import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import logo from "../src/img/logo.png";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Filiaedison International</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <div className="header">
          <Image src={logo} width={80} height={80} alt="Logo" />
          <h1>Filiaedison International</h1>
        </div>
      </nav>
      <main>
        <div>

        </div>
        <form>
          <h3 className="center">Contact Us</h3>
          <input
            name="name"
            type="text"
            className="feedback-input"
            placeholder="Name"
          />
           <input
            name="phone"
            type="number"
            className="feedback-input"
            placeholder="Phone No"
          />
          <input
            name="email"
            type="text"
            className="feedback-input"
            placeholder="Email"
          />
          <textarea
            name="text"
            className="feedback-input"
            placeholder="Message"
          ></textarea>
          <input type="submit" value="SUBMIT" />
        </form>
      </main>
      <footer>
        <small>
          &copy;{new Date().getFullYear()}{" "}
          <strong>Filiaedison International</strong>, All Rights Reserved
        </small>
      </footer>
    </>
  );
}
